/*
VFW Project 4
David Clark
03/02/13
*/

var json = {
	"loadout1":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test1"],
		"gearName": 	 ["Loadout Name:", "Test Loadout1"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "M4A1"],
		"magAmount": 	 ["Magazine Quantity:", "5"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout2":{
		"loadoutCat": 	 ["Loadout Category:", "Sniper"],
		"name": 		 ["Loadout Creator:", "Test2"],
		"gearName": 	 ["Loadout Name:", "Test Loadout2"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "SVD_Camo"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout3":{
		"loadoutCat": 	 ["Loadout Category:", "Sniper"],
		"name": 		 ["Loadout Creator:", "Test3"],
		"gearName": 	 ["Loadout Name:", "Test Loadout3"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "DMR"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout4":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test4"],
		"gearName": 	 ["Loadout Name:", "Test Loadout4"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "M16A2"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout5":{
		"loadoutCat": 	 ["Loadout Category:", "Support"],
		"name": 		 ["Loadout Creator:", "Test5"],
		"gearName": 	 ["Loadout Name:", "Test Loadout5"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "M249_SAW"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout6":{
		"loadoutCat": 	 ["Loadout Category:", "Support"],
		"name": 		 ["Loadout Creator:", "Test6"],
		"gearName": 	 ["Loadout Name:", "Test Loadout6"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "Mk_48_Mod_0"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout7":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test7"],
		"gearName": 	 ["Loadout Name:", "Test Loadout7"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "AK_74"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout8":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test8"],
		"gearName": 	 ["Loadout Name:", "Test Loadout8"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "AKS_74"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout9":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test9"],
		"gearName": 	 ["Loadout Name:", "Test Loadout9"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "AKS_74U"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout10":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test10"],
		"gearName": 	 ["Loadout Name:", "Test Loadout10"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "AKM"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout11":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test11"],
		"gearName": 	 ["Loadout Name:", "Test Loadout11"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "M4A3_CCO"],
		"magAmount": 	 ["Magazine Quantity:", "5"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout12":{
		"loadoutCat": 	 ["Loadout Category:", "Sniper"],
		"name": 		 ["Loadout Creator:", "Test12"],
		"gearName": 	 ["Loadout Name:", "Test Loadout12"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "M107"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout13":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test13"],
		"gearName": 	 ["Loadout Name:", "Test Loadout13"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "M14_AIM"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout14":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test14"],
		"gearName": 	 ["Loadout Name:", "Test Loadout14"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "M16A2_M203"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout15":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test15"],
		"gearName": 	 ["Loadout Name:", "Test Loadout15"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "M4A1_Holo"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout16":{
		"loadoutCat": 	 ["Loadout Category:", "Recon"],
		"name": 		 ["Loadout Creator:", "Test16"],
		"gearName": 	 ["Loadout Name:", "Test Loadout16"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "M4A1_CCO_SD"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout17":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test17"],
		"gearName": 	 ["Loadout Name:", "Test Loadout17"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "M4A1_CCO"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout18":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test18"],
		"gearName": 	 ["Loadout Name:", "Test Loadout18"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "L85A2"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout19":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test19"],
		"gearName": 	 ["Loadout Name:", "Test Loadout19"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "FN_FAL_ANPVS4"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	},
	"loadout20":{
		"loadoutCat": 	 ["Loadout Category:", "Assault"],
		"name": 		 ["Loadout Creator:", "Test20"],
		"gearName": 	 ["Loadout Name:", "Test Loadout20"],
		"dateAdded":	 ["Date Added:", "03/01/2013"],
		"weaponChoices": ["Weapon Choice", "FN_FAL"],
		"magAmount": 	 ["Magazine Quantity:", "10"],
		"grenade": 		 ["Grenade?", "Grenade"],
		"food": 		 ["Food?", "Food"],
		"drink": 		 ["Drink?", "Drink"],
		"medicine": 	 ["Medicine?", "Medicine"],
		"comments": 	 ["Comments:", "This is just a test loadout."]
	}

}